CREATE TABLE IF NOT EXISTS users (
  login_id VARCHAR(18) NOT NULL
  , password VARCHAR(255) DEFAULT NULL
  , role VARCHAR(5) DEFAULT 'USER'
  , login_enabled BOOLEAN NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY(id)
);
